export * from './dr-patients.model';
export * from './dr-patients-popup.service';
export * from './dr-patients.service';
export * from './dr-patients-dialog.component';
export * from './dr-patients-remove-dialog.component';
export * from './dr-patients-detail.component';
export * from './dr-patients.component';
export * from './dr-patients.route';
export * from './dr-patients-info.component';
